/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fabi
 */
public class jfrmCalculadoraC extends javax.swing.JFrame {
    String entrada = "";
double numero1 = 0, numero2 = 0;
String operador = "";
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmCalculadoraC.class.getName());

    //Variables Reestringidas 
    public jfrmCalculadoraC() {
        initComponents();
        jtxtCantidad.setText("0");
        this.setTitle("Calculadora");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtCantidad = new javax.swing.JTextField();
        jbtnNum4 = new javax.swing.JButton();
        jbtnNum6 = new javax.swing.JButton();
        jbtnMulti = new javax.swing.JButton();
        jbtnNum5 = new javax.swing.JButton();
        jbtnNum1 = new javax.swing.JButton();
        jbtnNum2 = new javax.swing.JButton();
        jbtnNum3 = new javax.swing.JButton();
        jbtnResta = new javax.swing.JButton();
        jbtnNum0 = new javax.swing.JButton();
        jbtnAC = new javax.swing.JButton();
        jbtnIgual = new javax.swing.JButton();
        jbtnSuma = new javax.swing.JButton();
        jbtnNum7 = new javax.swing.JButton();
        jbtnNum8 = new javax.swing.JButton();
        jbtnNum9 = new javax.swing.JButton();
        jbtnDivi = new javax.swing.JButton();
        jbtnPunto = new javax.swing.JButton();
        jbtnPorcentaje = new javax.swing.JButton();
        jbtnBorrar1 = new javax.swing.JButton();
        jbtnRaiz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtCantidad.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jtxtCantidad.setText("0");

        jbtnNum4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbtnNum4.setText("4");
        jbtnNum4.addActionListener(this::jbtnNum4ActionPerformed);

        jbtnNum6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbtnNum6.setText("6");
        jbtnNum6.addActionListener(this::jbtnNum6ActionPerformed);

        jbtnMulti.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbtnMulti.setText("*");
        jbtnMulti.addActionListener(this::jbtnMultiActionPerformed);

        jbtnNum5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbtnNum5.setText("5");
        jbtnNum5.addActionListener(this::jbtnNum5ActionPerformed);

        jbtnNum1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbtnNum1.setText("1");
        jbtnNum1.addActionListener(this::jbtnNum1ActionPerformed);

        jbtnNum2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbtnNum2.setText("2");
        jbtnNum2.addActionListener(this::jbtnNum2ActionPerformed);

        jbtnNum3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbtnNum3.setText("3");
        jbtnNum3.addActionListener(this::jbtnNum3ActionPerformed);

        jbtnResta.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbtnResta.setText("-");
        jbtnResta.addActionListener(this::jbtnRestaActionPerformed);

        jbtnNum0.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbtnNum0.setText("0");
        jbtnNum0.addActionListener(this::jbtnNum0ActionPerformed);

        jbtnAC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnAC.setText("AC");
        jbtnAC.addActionListener(this::jbtnACActionPerformed);

        jbtnIgual.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbtnIgual.setText("=");
        jbtnIgual.addActionListener(this::jbtnIgualActionPerformed);

        jbtnSuma.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbtnSuma.setText("+");
        jbtnSuma.addActionListener(this::jbtnSumaActionPerformed);

        jbtnNum7.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbtnNum7.setText("7");
        jbtnNum7.addActionListener(this::jbtnNum7ActionPerformed);

        jbtnNum8.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbtnNum8.setText("8");
        jbtnNum8.addActionListener(this::jbtnNum8ActionPerformed);

        jbtnNum9.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbtnNum9.setText("9");
        jbtnNum9.addActionListener(this::jbtnNum9ActionPerformed);

        jbtnDivi.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbtnDivi.setText("/");
        jbtnDivi.addActionListener(this::jbtnDiviActionPerformed);

        jbtnPunto.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbtnPunto.setText(".");
        jbtnPunto.addActionListener(this::jbtnPuntoActionPerformed);

        jbtnPorcentaje.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbtnPorcentaje.setText("%");
        jbtnPorcentaje.addActionListener(this::jbtnPorcentajeActionPerformed);

        jbtnBorrar1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbtnBorrar1.setText("C");
        jbtnBorrar1.addActionListener(this::jbtnBorrar1ActionPerformed);

        jbtnRaiz.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbtnRaiz.setText("√");
        jbtnRaiz.addActionListener(this::jbtnRaizActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnBorrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtxtCantidad)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbtnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbtnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jbtnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbtnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jbtnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jbtnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jbtnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbtnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jbtnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jbtnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jbtnDivi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBorrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDivi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum1ActionPerformed
        // TODO add your handling code here:
        entrada=entrada +1;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum1ActionPerformed

    private void jbtnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum2ActionPerformed
        // TODO add your handling code here:
        entrada=entrada +2;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum2ActionPerformed

    private void jbtnNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum3ActionPerformed
        // TODO add your handling code here:
        entrada=entrada +3;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum3ActionPerformed

    private void jbtnNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum4ActionPerformed
        // TODO add your handling code here:
        entrada=entrada +4;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum4ActionPerformed

    private void jbtnNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum5ActionPerformed
        // TODO add your handling code here:
        entrada=entrada +5;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum5ActionPerformed

    private void jbtnNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum6ActionPerformed
        // TODO add your handling code here:
        entrada=entrada +6;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum6ActionPerformed

    private void jbtnNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum7ActionPerformed
        // TODO add your handling code here:
        entrada=entrada +7;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum7ActionPerformed

    private void jbtnNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum8ActionPerformed
        // TODO add your handling code here:
        entrada=entrada +8;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum8ActionPerformed

    private void jbtnNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum9ActionPerformed
        // TODO add your handling code here:
        entrada=entrada +9;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum9ActionPerformed

    private void jbtnNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum0ActionPerformed
        // TODO add your handling code here:
        entrada=entrada +0;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum0ActionPerformed

    private void jbtnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRestaActionPerformed
        // TODO add your handling code here:
        if (!entrada.equals("")) {
        numero2 = Double.parseDouble(entrada);
        
        if (operador.equals("+")) {
            numero1 = numero1 + numero2;
        } else if (operador.equals("-")) {
            numero1 = numero1 - numero2;
        } else if (operador.equals("*")) {
            numero1 = numero1 * numero2;
        } else if (operador.equals("/")) {
            numero1 = numero1 / numero2;
        } else {
            numero1 = numero2;
        }
        
        jtxtCantidad.setText(String.valueOf(numero1));
        entrada = "";
    }
        
    operador ="-";
    }//GEN-LAST:event_jbtnRestaActionPerformed

    private void jbtnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultiActionPerformed
        // TODO add your handling code here:
        if (!entrada.equals("")) {
        numero2 = Double.parseDouble(entrada);
        
        if (operador.equals("+")) {
            numero1 = numero1 + numero2;
        } else if (operador.equals("-")) {
            numero1 = numero1 - numero2;
        } else if (operador.equals("*")) {
            numero1 = numero1 * numero2;
        } else if (operador.equals("/")) {
            numero1 = numero1 / numero2;
        } else {
            numero1 = numero2;
        }
        
        jtxtCantidad.setText(String.valueOf(numero1));
        entrada = "";
    }
        
    operador ="*";
    }//GEN-LAST:event_jbtnMultiActionPerformed

    private void jbtnDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDiviActionPerformed
        // TODO add your handling code here:
        if (!entrada.equals("")) {
        numero2 = Double.parseDouble(entrada);
        
        if (operador.equals("+")) {
            numero1 = numero1 + numero2;
        } else if (operador.equals("-")) {
            numero1 = numero1 - numero2;
        } else if (operador.equals("*")) {
            numero1 = numero1 * numero2;
        } else if (operador.equals("/")) {
            numero1 = numero1 / numero2;
        } else {
            numero1 = numero2;
        }
        
        jtxtCantidad.setText(String.valueOf(numero1));
        entrada = "";
    }
        
    operador ="/";
    }//GEN-LAST:event_jbtnDiviActionPerformed

    private void jbtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSumaActionPerformed
        // TODO add your handling code here:
        if (!entrada.equals("")) {
        numero2 = Double.parseDouble(entrada);
        
        if (operador.equals("+")) {
            numero1 = numero1 + numero2;
        } else if (operador.equals("-")) {
            numero1 = numero1 - numero2;
        } else if (operador.equals("*")) {
            numero1 = numero1 * numero2;
        } else if (operador.equals("/")) {
            numero1 = numero1 / numero2;
        } else {
            numero1 = numero2;
        }
        
        jtxtCantidad.setText(String.valueOf(numero1));
        entrada = "";
    }
        
    operador ="+";
    }//GEN-LAST:event_jbtnSumaActionPerformed

    private void jbtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIgualActionPerformed
        // TODO add your handling code here:
        double resultado;
        numero2=Integer.parseInt(entrada);
        jtxtCantidad.setText("");
        entrada="";
        
        if (operador.equals("*")) {
            resultado=numero1*numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        }
        if(operador.equals("-")){
        resultado=numero1-numero2;
        entrada=String.valueOf(resultado);
        jtxtCantidad.setText(entrada);
        }
        if(operador.equals("/")){
        resultado=numero1/numero2;
        entrada=String.valueOf(resultado);
        jtxtCantidad.setText(entrada);
        }
        if(operador.equals("+")){
        resultado=numero1+numero2;
        entrada=String.valueOf(resultado);
        jtxtCantidad.setText(entrada);
        }
        
    }//GEN-LAST:event_jbtnIgualActionPerformed

    private void jbtnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnACActionPerformed
        // TODO add your handling code here:
        entrada="";
    numero1 = 0;
    numero2 = 0;
    jtxtCantidad.setText("0");
    }//GEN-LAST:event_jbtnACActionPerformed

    private void jbtnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPuntoActionPerformed
        // TODO add your handling code here:
        if (!entrada.contains(".")) {
         if (entrada.equals("")) {
             entrada = "0.";
         } else {
             entrada = entrada + ".";
         }
         jtxtCantidad.setText(entrada);
        }
    }//GEN-LAST:event_jbtnPuntoActionPerformed

    private void jbtnPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPorcentajeActionPerformed
        // TODO add your handling code here:
        double valor = Double.parseDouble(entrada);
    valor = valor / 100;
    entrada = String.valueOf(valor);
    jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnPorcentajeActionPerformed

    private void jbtnBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBorrar1ActionPerformed
        // TODO add your handling code here:
        if (entrada.length() > 1) {
        entrada = entrada.substring(0, entrada.length() -  1);
    } else {
            entrada = "";
    }
        
    if (entrada.equals("")) {
        jtxtCantidad.setText("0");
    } else {
        jtxtCantidad.setText(entrada);
    }
    }//GEN-LAST:event_jbtnBorrar1ActionPerformed

    private void jbtnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRaizActionPerformed
        // TODO add your handling code here:
        double valor = Double.parseDouble(entrada);
        
    if (valor >= 0) {
        valor = Math.sqrt(valor);
        entrada = String.valueOf(valor);
    } else {
        entrada = "Error";
    }
    
    jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnRaizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmCalculadoraC().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnAC;
    private javax.swing.JButton jbtnBorrar1;
    private javax.swing.JButton jbtnDivi;
    private javax.swing.JButton jbtnIgual;
    private javax.swing.JButton jbtnMulti;
    private javax.swing.JButton jbtnNum0;
    private javax.swing.JButton jbtnNum1;
    private javax.swing.JButton jbtnNum2;
    private javax.swing.JButton jbtnNum3;
    private javax.swing.JButton jbtnNum4;
    private javax.swing.JButton jbtnNum5;
    private javax.swing.JButton jbtnNum6;
    private javax.swing.JButton jbtnNum7;
    private javax.swing.JButton jbtnNum8;
    private javax.swing.JButton jbtnNum9;
    private javax.swing.JButton jbtnPorcentaje;
    private javax.swing.JButton jbtnPunto;
    private javax.swing.JButton jbtnRaiz;
    private javax.swing.JButton jbtnResta;
    private javax.swing.JButton jbtnSuma;
    private javax.swing.JTextField jtxtCantidad;
    // End of variables declaration//GEN-END:variables
}
